plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.107'
}

base {
    archivesName = 'pe_wars-neoforge-1.21.1'
}

neoForge {
    version = '21.1.172'

    runs {
        client {
            client()
        }
    }

    mods {
        pe_wars {
            sourceSet sourceSets.main
        }
    }
}

jar {
    manifest {
        attributes([
                'Specification-Title'     : 'pe_wars',
                'Specification-Vendor'    : 'politempire',
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.version,
                'Implementation-Vendor'   : 'politempire'
        ])
    }
}
